### ISSUE TITLE
Always crashes when running v0.12.1.x on Testnet on Mac OSX

### ISSUE THREAD

**Issue by ghost** [dashpay/dash#1002]
Assertion failed: (onlyMaybeDeadlock), function potential_deadlock_detected, file sync.cpp, line 111.
Abort trap: 6

This is with the current latest code commit d81e729b0af77a66844e87858ccc7f109f19fdc6
Built on Mac OSX

Seems repeatable since it happens every time for me although not immediately

**Comment by tgflynn** [comment]
This should only happen if you configured with --enable-debug.  If you do that you will currently get many crashes.

I suggest you do a git clean -f -x -d and reconfigure without that option.

**Comment by dashascash** [comment]
Thanks, but don't I need "--enable-debug" if I want to use the debugger?

**Comment by tgflynn** [comment]
Not necessarily debugging symbols are turned on by default.

However when debugging people also often want to compile with `-O0` so that they aren't confused by compiler optimizations.  That is enabled by --enable-debug.  Unfortunately in 0.12.1 that option also enables the DEBUG_LOCKORDER macro which is only intended for debugging mutex locking logic and by design causes many crashes.

I think we should revert this to the way it was in 0.12.0 but in the meantime if you want to compile with 
`-O0` you can either edit configure.ac  and remove `-DDEBUG_LOCKORDER` from the only line that contains it (will need to run autogen.sh after making the change) or you can try configuring like this:

`./configure CXXFLAGS=-O0 CFLAGS=-O0`

I'm not 100% the second method will work but you can check if the right compiler flags were picked up by building with:

`make V=1`

**Comment by dashascash** [comment]
Great, thanks. Feel free to close issue
