### ISSUE TITLE
Mac Wallet Will Not Open Config Files

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1100]
Choosing "Open Wallet Configuration File" or "Open Masternode Configuration File" from the Tools menu results in no action. Neither file is opened.

12.1 testnet

**Comment by mkinney** [comment]
I think this is because the .conf file is associated with another program, and it expects it to be of a certain length/format. You can confirm this by doing that action again, going into spotlight, and entering "console", then searching for "dash.conf". You should see some filtered lines like this:

Feb  2 18:38:56 mkinneymbp Tunnelblick[772]: Converting/Installing /Users/mikekinney/Library/Application Support/DashCore/dash.conf: File '/Users/mikekinney/Library/Application Support/DashCore/dash.conf' is too short (0 bytes).

On my mac, I have .conf files (for some reason) associated with the application 'Tunnelblick'. As such, it will not open the configuration file.

I'm a little stumped as to how to fix this programmatically (or via script). Perhaps another might know or have some ideas.

FYI, I added a comment to the dash.conf file:
# This is a test

Now, I get a prompt clearing asking to open the configuration file in Tunnelblick, as opposed to a silent UI failure.

**Comment by crowning-** [comment]
Yes, the wallet opens the .conf file with whatever application is the standard application for files with this extension.

Most operating systems allow to define/customize the default applications, so you have to configure a text-editor for this.

If needed I can provide more details later, right now I'm half a continent away from my Mac.

**Comment by UdjinM6** [comment]
"nothing to fix" rather then "wontfix" actually :)
