### ISSUE TITLE
building tweaks v0.12.1.x on mac (osx) and 'make check' fails

### ISSUE THREAD

**Issue by mkinney** [dashpay/dash#1289]
Is v0.12.1.x the active development branch? Should it pass the tests in 'make check'?

I was only able to build on mac using: 
   brew uninstall protobuf 
   brew install homebrew/versions/protobuf260 --c++11
   export CXXFLAGS=-std=c++11 
   ./configure

Which builds successfully. (Note: there are some warnings)

However, 'make check' fails. 

    /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
   FAIL: test/test_dash
   PASS: qt/test/test_dash-qt

   Testsuite summary for Dash Core 0.12.1

   TOTAL: 2
   PASS:  1
   SKIP:  0
   XFAIL: 0
   FAIL:  1
   XPASS: 0
   ERROR: 0
  See src/test-suite.log
  Please report to https://github.com/dashpay/dash/issues

[test-suite.log.txt](https://github.com/dashpay/dash/files/737003/test-suite.log.txt)
[dash_build_output_from_9c5db04.txt](https://github.com/dashpay/dash/files/737004/dash_build_output_from_9c5db04.txt)

Note: Changed the log file to end with .txt for github.

I would like to work on the doc (https://github.com/dashpay/dash/blob/v0.12.1.x/doc/build-osx.md_ and cleaning up the warnings, but not until the 'make check' works successfully.

**Comment by UdjinM6** [comment]
You shouldn't use C++11 to compile Dash Core, we don't fully support this yet. The reason why you may want to compile is probably because Qt5 5.7 (which is default for homebrew now iirc) requires C++11, so make sure to install Qt version < 5.6.2 (Qt5 5.6.2 has some other issues, 5.6.1-1 should work just fine): `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e6d954bab88e89c5582498157077756900865070/Formula/qt5.rb`

**Comment by mkinney** [comment]
Thanks.

I also had to run: (as protobuf v3.1 has issues)
  brew uninstall protobuf
  brew install homebrew/versions/protobuf260 --c++11
Also, the latest commit now passes the 'make check'.

Closing issue.
