### ISSUE TITLE
Successive instant  send  fails with  message that  is weird :Insufficient funds. InstantSend requires inputs with at least 6 confirmations, you might need to wait a few minutes and try again.

### ISSUE THREAD

**Issue by staier** [dashpay/dash#1725]
```
dash@dethline-HP-ProBook-6560b ~ $ dash-cli instantsendtoaddress "XfDyCr5Gj5ChuDuWZtMoW9ZJe8QN6crYUt" 0.1
b2df247cb0cec81fee5749af0c278826ae9fda3bef6e8a4910c2bed91226d76e
dash@dethline-HP-ProBook-6560b ~ $ dash-cli instantsendtoaddress "XfDyCr5Gj5ChuDuWZtMoW9ZJe8QN6crYUt" 0.1
error code: -4
error message:
Insufficient funds. InstantSend requires inputs with at least 6 confirmations, you might need to wait a few minutes and try again.
dash@dethline-HP-ProBook-6560b ~ $ dash-cli instantsendtoaddress "XfDyCr5Gj5ChuDuWZtMoW9ZJe8QN6crYUt" 0.1
error code: -4
error message:
Insufficient funds. InstantSend requires inputs with at least 6 confirmations, you might need to wait a few minutes and try again.

```
Using  sendto address  is no different

```

dash@dethline-HP-ProBook-6560b ~ $ dash-cli sendtoaddress "XfDyCr5Gj5ChuDuWZtMoW9ZJe8QN6crYUt" 0.1 "" "" false true
error code: -4
error message:
Insufficient funds. InstantSend requires inputs with at least 6 confirmations, you might need to wait a few minutes and try again.
dash@dethline-HP-ProBook-6560b ~ $ dash-cli --version
Dash Core RPC client version v0.12.2.0
dash@dethline-HP-ProBook-6560b ~ $```

**Comment by thephez** [comment]
**Note: InstantSend has been temporarily disabled (since the end of August), so using it would only result in paying higher fees with no benefit.**  It will be re-enabled once DIP-1 is activated.  See this [forum post](https://www.dash.org/forum/threads/temporary-disabling-of-instandsend-due-to-potential-quorum-exploit-method.16492/) for info.

A couple possible reasons for the error message:
1. The most straightforward explanation is that one or more of the inputs to the transaction doesn't have enough confirmations as the error suggests.  Every input to an IS transaction must have 6+ confirmations.  

1. I don't recall if the Dash Core wallet prevents you from doing an IS transaction when it is disabled.  If not,  that could be the reason for the error.

If you're interested in the technical details of IS (and the reason it was disabled), check out [this video about] it(https://www.youtube.com/watch?v=n4PELomRiFY).

**Comment by staier** [comment]
The  first  reason does not  apply   in my  case as all funds are old.
My  point  is exactly  that  the message is  misleading.

**Comment by staier** [comment]
also   the weird thing  is  the first  transaction  is successfull,  but  consecutive ones  fail

**Comment by thephez** [comment]
Okay, I see what's going on (at least in the first example you listed with address XfD...YUt).  The first IS transaction is sent fine (because all inputs have 6+ confirmations).  The second IS transaction fails because it is constructed using the remaining value from the first transaction as an input (which does *not* have 6+ confirmations - at most it could have had 5 confirmations IF the previous InstantSend transaction was already approved by the masternodes).  

You can see it clearly on a block explorer ([second Tx](https://explorer.dash.org/tx/8cf55db71e6f281ab8391a25954ae4e42e66cb869af353cba2dfca2e8c9b91bb#o0) is using output 1 from the [first Tx](https://explorer.dash.org/tx/b2df247cb0cec81fee5749af0c278826ae9fda3bef6e8a4910c2bed91226d76e#o0)).

**Comment by staier** [comment]
Thank you.
Just  to  double  check:
Are you  saying  that   the error is correct  ,  and  the problem  is  i  only  have funds  that  is a change from  first  transaction ,  so  i  need to wait  until 6 confirmation coming?

That  makes sense,  maybe the  case actually ,  i need to  check.

One question  though  ,  is there a logic in place to  select  coins with  enough confirmations in case  there are  ones in the  wallet?

**Comment by thephez** [comment]
Yes, the error is correct in this case.  I am not sure about the coin selection.

**Comment by staier** [comment]
looks like a non- issue ,  thanks @thephez  for clarifying
