### ISSUE TITLE
 dashd: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by famfamfam** [dashpay/dash#1762]
When I try exec command dashd I have a error
> dashd: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory

> find /usr/local/lib -iname 'libdb_cxx*'
> /usr/local/lib/libdb_cxx-4.8.so
> /usr/local/lib/libdb_cxx-4.8.la
> /usr/local/lib/libdb_cxx-4.8.a
> /usr/local/lib/libdb_cxx.a
> /usr/local/lib/libdb_cxx.so
> /usr/local/lib/libdb_cxx-4.so

CentOS 7

**Comment by nmarley** [comment]
Hi, thanks for reporting! Can you provide more information on exactly how to reproduce this?

One thing I'd note is that (from the `man ld` on CentOS 7):

> The linker uses the following search paths to locate required shared libraries:
> ...
> 5.  For a native linker, search the contents of the environment variable "LD_LIBRARY_PATH".
> 6.  For a native ELF linker, the directories in "DT_RUNPATH" or "DT_RPATH" of a shared library are searched for shared libraries needed by it. The "DT_RPATH" entries are ignored if "DT_RUNPATH" entries exist.
> 7.  The default directories, normally /lib and /usr/lib.
> 8.  For a native linker on an ELF system, if the file /etc/ld.so.conf exists, the list of directories found in that file.


... so what happens if you do:

```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
dashd
```

Another thing that might help is to show the output of:

```
ldd $(which dashd)
```

This should display the paths/files which the dynamic libraries should resolve to.


Can you try the above, and if that doesn't work, provide the exact steps used to reproduce your error (e.g. how did you download/build `dashd`, how did you get libdb_cxx* installed in `/usr/local/lib/`, etc.)?

**Comment by nmarley** [comment]
No reply for 3 months, assuming this is solved now, closing.

**Comment by scottie** [comment]
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
