### ISSUE TITLE
[Qt] Incorrect error message with Start Mixing and Passphrase entry

### ISSUE THREAD

**Issue by thephez** [dashpay/dash#1939]
This is an easy to duplicate issue (on the current develop branch - have not checked other versions) resulting in a misleading error message that could lead someone to think their wallet was locked when it actually is not.

1. Click the `Start Mixing` button while wallet is locked
2. Uncheck the `Only for mixing via PrivateSend` checkbox
![unlock - for all](https://user-images.githubusercontent.com/8145677/36396510-9edb0c02-158c-11e8-9058-0e3fbb468e45.png)
3. Enter correct passphrase and click `OK`
The wallet will report an incorrect error message as shown:
![unlock - erroneous error](https://user-images.githubusercontent.com/8145677/36396507-99d33a04-158c-11e8-9a60-d45be29c1cda.png)

The wallet is now unlocked (contrary to the error message). Also, mixing is not started.

I think the issue is due to the `requestUnlock` parameter [here](https://github.com/dashpay/dash/blob/develop/src/qt/overviewpage.cpp#L616) being decoupled from the actual state of the checkbox (the `fForMixingOnly` parameter is always true, not based on the checkbox state). This then results in `fMixingUnlockFailed` to be true (if the user supplied the correct password) because the new status of the wallet is `Unlocked`, not `UnlockedForMixingOnly` -
 [reference](https://github.com/dashpay/dash/blob/develop/src/qt/walletmodel.cpp#L597).

**Comment by UdjinM6** [comment]
Should be fixed by #1941 - no more such option on mixing, no issues :D

Speaking seriously though, letting users to unlock wallet for sending when starting mixing was probably not a good idea in the first place. With #1941 wallet will be unlocked for mixing only when user hits that button. Wallet still can be fully unlocked via menu (or rpc) for infinite amount of time or it will be unlocked temporary for sending via Send tab (and switch back to mixing only mode right after tx is sent if it was mixing atm) but in both cases it will ask for the passphrase to do so. This seems to be the optimal flow, pls test and confirm if it's working as expected now.

**Comment by thephez** [comment]
I agree - this seems to be the safest and most intuitive way to do this.

**Comment by UdjinM6** [comment]
Ok, closing this then :)
