### ISSUE TITLE
[Improvement] Processing blocks/reindexing blocks on disk could be optimized.

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#2063]
It appears that reindexing blocks and processing blocks is single threaded. It would improve performance a fair bit in the reindexing operation if it was multi-threaded. It could just be poorly optimized.

**Comment by sidhujag** [comment]
this is a trivial implementation.. pull in the cuckoo cache stuff and the concurrent thread processing for block verifications.

**Comment by PaulieD** [comment]
That's very possible. My only knowledge on it is that dash-qt.exe was running on 30% on a quad-core which makes it appear like it's on a single thread.

**Comment by jhodges10** [comment]
@PaulieD just because something is running at 30% on a quad-core doesn't mean it's single-threaded. There are a million different reasons that code could be running at less than 100% of CPU utilization, i.e. drive speed for reading the index, poorly done multi-threading, lack of proper caching to keep the CPU busy, or even a single part of the index operation like decompressing the block. 

Someone who knows the code better can chime but just from a cursory glance, I wouldn't necessarily jump to the lack of multi-threading conclusion.

**Comment by sidhujag** [comment]
The cache can be added, the multithreading is only happening when blocks are processed, so you may see it on reindex but during idle i doubt theres much happening to take advantage of multi-cores on the dash network

**Comment by DarrenTapp** [comment]
Related:  You may wish to review the giga_pref branch of the Bitcoin Unlimited Repository.

https://github.com/BitcoinUnlimited/BitcoinUnlimited/tree/giga_perf
