### ISSUE TITLE
dumphdinfo not giving output

### ISSUE THREAD

**Issue by anil215** [dashpay/dash#2069]
I have been trying to get the hdseed and mnemonic of my wallet using the dash-cli, i found that the call to dumphdinfo is not giving any output.
![screen shot 2018-05-06 at 3 32 19 am](https://user-images.githubusercontent.com/23135051/39667909-1f0574d0-50de-11e8-80ab-48172c21faf7.png)

Other calls like dumpwallet,importwallet are working fine. Am i missing something?

**Comment by thephez** [comment]
@anil215 Are you sure you are using an HD wallet? They are not enabled by default in the current version since support is still considered experimental. You would have had to use a command line option or add an entry to dash.conf to create an HD wallet. The result you are getting is the same thing I get when running that command on a standard (non-HD) wallet.

**Comment by PaulieD** [comment]
Hey @anil215, this should be fixed now in 12.3 :)

**Comment by UdjinM6** [comment]
fixed by #2134
