### ISSUE TITLE
Problem Cross-Compiling for Windows

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#2151]
Running on a Ubuntu 14.04, with 4 cores and 8gb of ram. I attempted to cross compile for windows, following the instructions provided in build-windows. It will not compile for me, here is the output. As you can see there, I tried to run `make clean` but it did not change anything

https://gist.github.com/PaulieD/7e50ca3c408987914b5ddc90814c28b6

When I built for linux, everything did exactly as is normal.

**Comment by PaulieD** [comment]
@wozniakk Same problem occurs after following nathan's steps in that issue

**Comment by wozniakk** [comment]
But any output from `update-alternatives` ?

**Comment by PaulieD** [comment]
output was as I would expect, it just asked which one I should switch to, and I chose the one mentioned in that issue

**Comment by buddilla** [comment]
If you want to do a "make deploy" make sure to have nsis installed. Good luck trying to get it to work for mac though. Even bitcoin has the same problem 
https://github.com/dashpay/dash/issues/2076
https://github.com/bitcoin/bitcoin/issues/13169

**Comment by PaulieD** [comment]
@buddilla Don't see how your comment is relevant. I'm not trying to use `make deploy`, but follow the instructions is build-windows and I'm not trying to compile for mac...

**Comment by aboutboy** [comment]
I had the same trouble...
first make, no problem, but no exe generated.
I tried again, but make error: 
**libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only**

detail log：
lce@lce-VirtualBox:~/dash-win$ make
Making all in src
make[1]: Entering directory '/home/lce/dash-win/src'
make[2]: Entering directory '/home/lce/dash-win/src'
make[3]: Entering directory '/home/lce/dash-win'
make[3]: Leaving directory '/home/lce/dash-win'
  CXX      crypto/libdashconsensus_la-aes.lo
  CXX      crypto/libdashconsensus_la-ripemd160.lo
  CXX      crypto/libdashconsensus_la-sha1.lo
  CXX      crypto/libdashconsensus_la-sha256.lo
  CXX      crypto/libdashconsensus_la-sha512.lo
  CXX      libdashconsensus_la-arith_uint256.lo
  CXX      consensus/libdashconsensus_la-merkle.lo
  CXX      libdashconsensus_la-hash.lo
  CXX      primitives/libdashconsensus_la-block.lo
  CXX      primitives/libdashconsensus_la-transaction.lo
  CXX      libdashconsensus_la-pubkey.lo
  CXX      script/libdashconsensus_la-dashconsensus.lo
  CXX      script/libdashconsensus_la-interpreter.lo
  CXX      script/libdashconsensus_la-script.lo
  CXX      libdashconsensus_la-uint256.lo
make[3]: Entering directory '/home/lce/dash-win/src/secp256k1'
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
/usr/bin/x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/home/lce/dash-win/src/secp256k1'
  CXXLD    libdashconsensus.la
crypto/.libs/libdashconsensus_la-hmac_sha256.o: In function `CHMAC_SHA256::CHMAC_SHA256(unsigned char const*, unsigned long)':
/home/lce/dash-win/src/crypto/hmac_sha256.cpp:16: undefined reference to `CSHA256::Write(unsigned char const*, unsigned long)'
/home/lce/dash-win/src/crypto/hmac_sha256.cpp:22: undefined reference to `CSHA256::Write(unsigned char const*, unsigned long)'
/home/lce/dash-win/src/crypto/hmac_sha256.cpp:26: undefined reference to `CSHA256::Write(unsigned char const*, unsigned long)'
crypto/.libs/libdashconsensus_la-hmac_sha256.o: In function `CHMAC_SHA256::Finalize(unsigned char*)':
/home/lce/dash-win/src/crypto/hmac_sha256.cpp:33: undefined reference to `CSHA256::Write(unsigned char const*, unsigned long)'
crypto/.libs/libdashconsensus_la-hmac_sha512.o: In function `CHMAC_SHA512::CHMAC_SHA512(unsigned char const*, unsigned long)':
/home/lce/dash-win/src/crypto/hmac_sha512.cpp:16: undefined reference to `CSHA512::Write(unsigned char const*, unsigned long)'
/home/lce/dash-win/src/crypto/hmac_sha512.cpp:22: undefined reference to `CSHA512::Write(unsigned char const*, unsigned long)'
/home/lce/dash-win/src/crypto/hmac_sha512.cpp:26: undefined reference to `CSHA512::Write(unsigned char const*, unsigned long)'
crypto/.libs/libdashconsensus_la-hmac_sha512.o: In function `CHMAC_SHA512::Finalize(unsigned char*)':
/home/lce/dash-win/src/crypto/hmac_sha512.cpp:33: undefined reference to `CSHA512::Write(unsigned char const*, unsigned long)'
...
collect2: error: ld returned 1 exit status
Makefile:4103: recipe for target 'libdashconsensus.la' failed
make[2]: *** [libdashconsensus.la] Error 1
make[2]: Leaving directory '/home/lce/dash-win/src'
Makefile:10560: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lce/dash-win/src'
Makefile:688: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by codablock** [comment]
It's strange that the fix proposed in #1751 does not help. Can you try this:
```
sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
sudo update-alternatives --set i686-w64-mingw32-g++  /usr/bin/i686-w64-mingw32-g++-posix
sudo update-alternatives --set x86_64-w64-mingw32-gcc  /usr/bin/x86_64-w64-mingw32-gcc-posix
sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
```
(these are the calls we use in Dockerfile.builder and they work)

**Comment by PaulieD** [comment]
Yes, that worked @codablock, after a couple of cleans and reclones etc. Interesting, not sure why it failed initially. Shouldn't we add those calls into the `build-windows` doc file?

**Comment by ScaMar** [comment]
update-alternatives are needed on ubuntu 18.04+, is it right?

**Comment by PaulieD** [comment]
I believe so @ScaMar

**Comment by vijaydasmp** [comment]
I am facing similar issue in WSL build https://github.com/dashpay/dash/issues/4346#issue-973178971
