### ISSUE TITLE
Additional information for masternode: Version: Unknown

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#2171]
Additional information for masternode, version info is **Unknown** in fully enabled and working masternode.
I noted that version info was shown and correct when status was PRE_ENABLED,
but then when status changed to ENABLED, version info also changed to Unknown.

Remote os: Ubuntu 15.04.
Local os: Win 7 64bit.
Dash version in both: v0.12.3.1.

**Comment by UdjinM6** [comment]
Thanks for reporting.  This behaviour is expected however - the issue is that 70208 and 70210 have a slightly different message structure. This dialog and a corresponding rpc (`masternodelist daemon`) should provide the info more accurately as more and more nodes migrate to 0.12.3.1. The issue should be completely fixed (for 0.12.3.x+ nodes) with spork6 activation.

**Comment by akijuh** [comment]
@UdjinM6 
Ok, then i close this.
