### ISSUE TITLE
debugging dash

### ISSUE THREAD

**Issue by LucaPaterlini** [dashpay/dash#2287]
hello,
today I have downloaded the lasted version of Dash and I have tried to start the debugger on c-lion.
and I have got this error.

34: error: expected ‘)’ before ‘host_16bits’
 inline uint16_t htole16(uint16_t host_16bits)

is there any manual on how to configure clion correctly to start debugging?

**Comment by nmarley** [comment]
Hi, I don't believe there is a manual for how to set up CLion. But this error looks to be syntax related. Please be sure to check out a clean copy of the code.

Or it might be that CLion isn't able to expand all the macro definitions, maybe because the build system is pretty nuanced. I would suggest using CLion to develop but build and debug manually.
