### ISSUE TITLE
If IS failed how to fall back to a normal transaction

### ISSUE THREAD

**Issue by tkblack** [dashpay/dash#2341]
I want to know if an IS is failed , how to handle the transaction ? If it fall back to a normal transaction , and if it will draw back  the fee of IS ?  Where is the source code about this ?

**Comment by thephez** [comment]
If a proposed IS transaction (a transaction sent using the `ix` message instead of `tx`) fails to obtain a lock for all inputs, it simply is treated as a normal (`tx`) transaction from that point forward. Nothing about the transaction changes (i.e. there is no fee change, etc.). 

I would suggest starting in [instantx.cpp](https://github.com/dashpay/dash/blob/master/src/instantx.cpp) if you are interested in the code.

**Comment by tkblack** [comment]
Thanks, can i get some testnet coins for test？ I will send back as soon as possible.
address : yXPCk5TCizy4U6KEYYVdXjtuBtunr6nzNS

**Comment by thephez** [comment]
You can get testnet coins from a [faucet](https://docs.dash.org/en/latest/developers/testnet.html#faucets). Looks like a number of them are dry, but this one worked - http://faucet.test.dash.crowdnode.io/.

**Comment by tkblack** [comment]
OK,thanks for u help!

**Comment by thephez** [comment]
:+1: Can this issue be closed now?

**Comment by tkblack** [comment]
I know masternodes vote IS are selected by the last block hash,but ,what will happen if most of elected masternodes are offline ? Every IX are simply failed?

**Comment by PastaPastaPasta** [comment]
5 out of 10 of the Masternodes would have to go offline at the same time for what you said to be a problem. Some IS txs do fail to get verified and have to revert back to blockchain confs, but it is definitely not common

**Comment by tkblack** [comment]
OK,thank u!
