### ISSUE TITLE
QT font issues no matter the display option

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#2565]
I've seen font issues forever in dash-qt. Unsure what the real culprit is, but this example is the most egregious, I think...

Fedora LInux 28
QT 5.11.1
Hardware: QHD+ screen at something like 2048 x 1152
Window Manager: GNOME 3.28
Display server: Wayland, but...
dash-qt set to use X11 display server protocol (as opposed to Wayland which has issues with QT5)

Note: dash-qt using DASH-traditional is definitely the best user experience (fonts, spacing, etc, but still screws up this screen.

Image...
![screenshot from 2018-12-18 07-48-53](https://user-images.githubusercontent.com/6908872/50155982-84a36d00-029b-11e9-9628-e3a87c5afd67.png)

**Comment by strophy** [comment]
I've seen similar problems under Windows at 2880x1620 (200% scaling) forever as well. Bitcoin discussed this upstream in [#6472](https://github.com/bitcoin/bitcoin/issues/7341) and [#7341](https://github.com/bitcoin/bitcoin/issues/7341) and resolved it in [#8210](https://github.com/bitcoin/bitcoin/pull/8210) by updating to Qt 5.6.1. Dash should have inherited this, since we are already on Qt 5.7.1, but I suspect the Dash themes still define parts of the interface (particularly PrivateSend) using pixel values instead of ratios. I think Dash-traditional looks OK because it is based on Bitcoin and has their fixes, but the Dash themes need some serious work still.

If I was going to try and take a look at this, where would I start?

**Comment by PastaPastaPasta** [comment]
I think this has been resolved? (with the latest GUI redo) If not please feel free to reopen
