### ISSUE TITLE
develop HEAD crashes during block verification

### ISSUE THREAD

**Issue by rex4539** [dashpay/dash#2610]
### Describe the issue
App crashes during block verification.

### Can you reliably reproduce the issue?
Always

#### If so, please list the steps to reproduce below:
1. Launch app.

### Expected behaviour
App does not crash.

### Actual behaviour
```
Assertion failed: (hashBestBlock == hashBlockIndex), function VerifyBestBlock, file evo/evodb.cpp, line 22
```
Then app crashes.

### What version of Dash Core are you using?
develop HEAD

### Machine specs:
- OS: OS X 10.11.6 (15G22010)
- CPU: Intel Core 2 Duo 2,4 GHz
- RAM: 4 GB
- Disk size: 1TB
- Disk Type (HD/SDD): HD

**Comment by UdjinM6** [comment]
I guess this happens when you upgrade from `v0.12.3.x`/`master` to `develop`. This is by design because we have to ensure EvoDB consistency (i.e. to make sure it has all the data about deterministic masternodes from the very first block since DIP3 activation). We'll mention this in release note but I see how this can be confusing because... no one reads instructions :) I think #2611 should clarify the issue a bit and lower the number of similar questions we might get from users who are late to this upgrade.

**Comment by rex4539** [comment]
This is not the case for me. I have been on the `develop` branch for over a year :)

I have restarted the client with `--reindex-chainstate` and currently indexing for for hours on end...

Hopefully that will fix it.

**Comment by UdjinM6** [comment]
>This is not the case for me. I have been on the develop branch for over a year :)

Hmmm true, upgrading from `master` to `develop` is not the only case :) This can still happen if the last time you compiled and launched your wallet/node like a month or so ago.

**Comment by rex4539** [comment]
`--reindex-chainstate` fixed it.
