### ISSUE TITLE
Whitepaper: figure 6 resolution

### ISSUE THREAD

**Issue by olivbau** [dashpay/dash#3180]
### Describe the issue
In the whitepaper (github Wiki and PDF), the figure 6: Mining Reward Schedule (5.2) is low resolution, which makes it hard to read.

https://github.com/dashpay/dash/wiki/images/img09.png

### Expected
Higher resolution image

**Comment by strophy** [comment]
I have drawn the top chart again based on [moo's data available here](https://docs.google.com/spreadsheets/d/1JUK4Iy8pjTzQ3Fvc-iV15n2qn19fmiJhnKDDSxebbAA/edit#gid=205877544), with the [result visible here](https://docs.google.com/spreadsheets/d/e/2PACX-1vTtmZNmNU-t25Ffy98xKbFzJD7R61JZKYhuWSpK-4zFYSto0kv5k6zUx59fL7dj-TeaOFohDGmMj36X/pubchart?oid=1021105075&format=interactive). A few spot checks seem to indicate that the historical and projected coin emission in that document remain valid. 

But it's important to point out that the chart in the original whitepaper was describing Evan's planned variable coin emission based on hashrate and difficulty, which resulted in the low absolute minimum supply. Since it is unlikely that hashrate will fall low enough to make this scenario plausible, the difference in min/max coin supply is actually showing the split between zero/full allocation of the budget. I think it is probably not worth updating this, since the original data for the chart is no longer available, but should be kept around for historical reasons. Thoughts?

**Comment by PastaPastaPasta** [comment]
This can probably be closed. Either way, here isn't the best place to discuss problems with the whitepaper
