### ISSUE TITLE
I forked Dash, but I can't open the wallet because of this message "Invalid spork address specified"

### ISSUE THREAD

**Issue by BenCryptoKing** [dashpay/dash#3406]
Hi, man! How exactly can I disable spork address at init.cpp from the source code?
I forked dash, but I can't open the wallet!

**Comment by nmarley** [comment]
Hi, can you explain more what you're trying to do? We haven't been supporting forks due to limited resources, but might be able to point you in the right direction.

You can't really disable the spork address, but you can generate your own spork key from any ECDSA private key pair. Just make sure you have the private key so you can sign sporks, and replace the spork address w/your own address in `chainparams.cpp`.

**Comment by MonkeyD-Core** [comment]
how to sign the spork ?

**Comment by PastaPastaPasta** [comment]
duplicate of https://github.com/dashpay/dash/issues/3455, plus no response. Closing
