### ISSUE TITLE
TESTNET3 ISSUE

### ISSUE THREAD

**Issue by Khaos-Labs** [dashpay/dash#3957]
The problem of synchronization block in test network is checkforkwarning conditions: 
warning: found invalid chain at learn ~ 6 blocks longer than our best chain

2021-01-21 11:00:29 ERROR: AcceptBlockHeader: block 00000674c5269b59d6d3bb6bb08b58add4b3e0eab11136be47bb8e0d4ec86e69 is marked invalid

Execution by command ： ./dash-cli -conf=dashcoin.conf reconsiderblock 00000674c5269b59d6d3bb6bb08b58add4b3e0eab11136be47bb8e0d4ec86e69

In the end, it was the same mistake。 
please help ！！！ ths。

**Comment by wangke0809** [comment]
I met the same question.

**Comment by thephez** [comment]
It seems you may not be running the latest RC (0.17.0-RC2: https://github.com/dashpay/dash/releases/tag/v0.17.0.0-rc2). The v17 BIP9 activation on testnet happened at block 414100 and likely forked your client off due to it being an outdate version. The block hash you list is for block [414106](https://testnet-insight.dashevo.org/insight/block/00000674c5269b59d6d3bb6bb08b58add4b3e0eab11136be47bb8e0d4ec86e69) and it is a valid block on the correct chain.

```
    "v17": {
      "status": "active",
      "startTime": 1606780800,
      "timeout": 1638316800,
      "since": 414100
    }
```
