### ISSUE TITLE
V12 masternodes stuck on status 3, eventually go offline

### ISSUE THREAD

**Issue by nmarley** [dashpay/dash#533]
With V12, not seeing the "HotCold enabled" message at all in the debug.log. Currently I'm getting 2 different statuses with "masternode status" from the masternodes, "Wallet is locked." and "Could not find suitable coins". I'm also getting these random addresses in the "pubKeyMasternode" status field, that i've never seen before. Those aren't my masternode pubkeys. :/.

    $ ./current_dash/bin/dash-cli masternode status
    {
        "vin" : "CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )",
        "service" : "XXX.XXX.XX.XX:9999",
        "status" : 3,
        "pubKeyMasternode" : "XXXXXX",
        "notCapableReason" : "Wallet is locked."
    }

    $ ../current_dash/bin/dash-cli masternode status
    {
    "vin" : "CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )",
    "service" : "XXX.XXX.XXX.XX:9999",
    "status" : 3,
    "pubKeyMasternode" : "XxLD1pQ8HjhMgrTTMBfdUBDsBbqnNXKqbt",
    "notCapableReason" : "Could not find suitable coins!"
    }

The pubKeyMasternode address shown here is not one of my known addresses.

**Comment by dutchn0mad** [comment]
Getting the same results as nmarley with the following messages in .dash/debug.log:

<code>2015-08-15 12:12:10 CActiveMasternode::ManageStatus() - Checking inbound connection to 'x.x.x.x:9999'
2015-08-15 12:12:10 CActiveMasternode::GetMasterNodeVin - Could not locate specified vin from possible list
2015-08-15 12:12:10 CActiveMasternode::ManageStatus() - Could not find suitable coins!</code>

**Comment by UdjinM6** [comment]
Problem:
You have masternode in list but `dash-cli masternode debug` gives you `Could not find suitable coins!`. Few hours later you node drops out of list.

Explanation:
This means that your node was not activated actually. On a successfully activated remote masternode `dash-cli masternode debug` should return `Masternode successfully started`. One reason why your masternode wasn't activated could be that new activation message can't reach your masternode from your local wallet because somewhere on its route there are only v11 masternodes and they just ignore new messages.

Fix:
To fix this you need to connect to your node directly and there are few ways to do this:
1) simple one, temporary: open console in local wallet and type `addnode MNIP onetry` - this will force your client to open direct connection to your MN
2) if #1 didn't work for some reason or you want to force your wallet to connect to your MNs every time you run it: add `-connect=MNIP` in command line or add `connect=MNIP` in dash.conf. You can add it multiple times if you have many masternodes. Note: this way your client will connect only to specified IPs.

This problem should go away once we have enough MNs updated to v12.

**Comment by UdjinM6** [comment]
@nmarley @dutchn0mad was the issue resolved or do you still have any problems?

PS. random address on `masternode status` is ok, it's used for debugging purposes and format will be changed if/when #562 will be merged

**Comment by nmarley** [comment]
Yes, issue is resolved. Thanks.

**Comment by UdjinM6** [comment]
@nmarley cool, thanks!
Closing this then.
