### ISSUE TITLE
TESTNET Forked on v19

### ISSUE THREAD

**Issue by SomethingUseful** [dashpay/dash#5436]
### Describe the issue
cant sync testnet3 after v19 activation today. stuck on 905217

#### If so, please list the steps to reproduce below:
1. tried -reindex; still forked
2. tried deleting everything; /blocks, /indexes /chainstate, peers.dat; still forks 

### Expected behaviour
syncs correctly.

### Actual behaviour
ERROR: ContextualCheckBlockHeader: forked chain older than last checkpoint (height 849624)
2023-06-14T19:16:35Z ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000398f3cc6ae440a1c66dad9e68ca4f9b03ff2f56fe5cce1b0a89f8aac3d, bad-fork-prior-to-checkpoint (code 67)

### What version of Dash Core are you using?
dashcore-19.1.0-x86_64-linux-gnu.tar.gz

### Machine specs:
- OS: linux
- CPU: plenty
- RAM: plenty
- Disk size: plenty
- Disk Type (HD/SDD): SDD

**Comment by PastaPastaPasta** [comment]
That is correct; please see and upgrade to the latest release candidate: https://github.com/dashpay/dash/releases/tag/v19.2.0-rc.1

In our upgrading to this release candidate, we deliberately hard forked and reorganized the chain so that we could re-experience the v19 hard fork and ensure proper activation. 

We communicated this plan during the Sprint Review livestream, and on discord. Sorry for any confusion.

**Comment by SomethingUseful** [comment]
synced OK with v19.2.0-rc.1
