### ISSUE TITLE
Possible memory leak with Dash Core v20.04 

### ISSUE THREAD

**Issue by qwizzie** [dashpay/dash#5872]
OS :	Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-169-generic x86_64)
Dashmate : 0.25.21
Dash Core : 20.0.4

CPU	 : Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz / 8 cores
RAM : 24GB
Storage :	600GB
Masternode type : Evonode on Mainnet

dashd.pid : 21-1-2024 (startdate)

![304719667-b3575ca7-35bd-42b1-ba3b-7b88fafa7a9f](https://github.com/dashpay/dash/assets/6610543/d60a1860-6676-4c12-a828-bdeab5fdc01e)

Is this daily increase of Memory Usage normal for this Evonode currently operating on Mainnet ? Perhaps it is normal Ubuntu behavior, where Ubuntu is slowly reserving unused RAM over time or is there a memory leak occurring here from either dashd or from Dashmate / Docker ?

Memory usage is fetched through a shell script and is scripted as follows (with its output added into a log file on a daily basis) : 

get_memory_usage() {
  memory_usage=$(free -m | awk '/Mem/ {print $3}')
  echo "Memory Usage: ${memory_usage}MB"
}

**Update** : turns out that above logging does not affirm or deny a possible memory leak with v20.0.4 as logging of dashd process memory is missing. This has been added and updated in my next comment.

**Comment by kxcd** [comment]
Hi Qwizzie, thanks for looking into this, unfortunately, one of the issues with Chat GPT-4 is that is makes people think they are more capable than they really are and important nuance is missing which may help explain what you are seeing.

Firstly, your script is simply fetching the used memory of the entire system, of which `dashd` is just one process, we need to hone in more specifically before pointing the finger of blame.  Also, please note that on a Linux system it will quickly use almost all available RAM with buffers and caches, this is desirable since disk is very slow in comparison to RAM and thus if we have spare RAM, why not turn it into a RAM disk?  The impact of this design approach to the OS is that it will appear that RAM is always depleted, but that is not the case you have to look deeper.

There are a couple of things we can do to monitor the memory usage of the `dashd`, at the OS level, we can run something like.

    ps -opid,vsz,cmd -C dashd

Which will get the size of the virtual memory of the process named `dashd` in kilobytes.  This will represent the amount of RAM the application is requesting, however, the actual amount of RAM it is using will be far lower, an optimisation in the DMZ accounts for this giving MNOs the ability to overcommit RAM and thus not get a OOM, but I digress.  Please re-run your cron and monitor this number and let us know the results.

I would also like to suggest to monitor the RAM usage from within the Daemon itself, please investigate the RPC.

    dash-cli getmemoryinfo

Which could be useful for the devs when it comes to debugging.  Of course the `dashd` could be lying, so the OS reported usage will be more useful to us.  From my testing, the node reaches something like 12GB virtual RAM in size and stops growing at that point and runs for weeks on end.  I feel this release is very stable and I see no leak on my end.

**Comment by qwizzie** [comment]
> Hi Qwizzie, thanks for looking into this, unfortunately, one of the issues with Chat GPT-4 is that is makes people think they are more capable than they really are and important nuance is missing which may help explain what you are seeing.

Strange reaction when i simply ask if this is normal Ubuntu behavior or a possible memory leakage from either dashd or Docker. No need to belittle me. 

> Please re-run your cron and monitor this number and let us know the results.

I am not running a cron job, i am running a shell script that executes itself once a day

```
#!/bin/bash

# Function to get CPU usage
get_cpu_usage() {
  cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')
  echo "CPU Usage: ${cpu_usage}%"
}

# Function to get memory usage
get_memory_usage() {
  memory_usage=$(free -m | awk '/Mem/ {print $3}')
  echo "Memory Usage: ${memory_usage}MB"
}

# Function to get disk usage
get_disk_usage() {
  disk_usage=$(df -h / | awk '/\// {print $5}')
  echo "Disk Usage: ${disk_usage}"
}

# Function to log data
log_data() {
  echo "$(date) - $(get_cpu_usage) - $(get_memory_usage) - $(get_disk_usage)" >> hardware.log
}

# Main function
main() {
  while true; do
    log_data
    sleep 24h  # Run once a day
  done
}

# Execute the main function
main &

# Notify user that the script is running in the background
echo "Script is running in the background. You can close the terminal."
```

I will look into adjusting above shell script so that it starts logging your recommended ps -opid,vsz,cmd -C dashd and see what that shows over time.

Thank you.

**Comment by QuantumExplorer** [comment]
@dashpay/core-team are you seeing the same?

**Comment by qwizzie** [comment]
Is it not problematic that Docker seems to be reserving between 16GB & 18GB  of my 24GB RAM and is not showing signs of stopping ? xkcd mentioned that he saw dashd memory utilization increased to 12GB and then it stablized and did not increase any further. I assume he was talking about Masternode Zeus. That is not what i am seeing with Docker. 

The following on itself is alarming for me : 

Evonode 1 (dashd.pid startdate 18th of January 2024)
RAM : 24GB

Mon 19 Feb 2024 12:27:56 PM - CPU Usage: 0.8% - Memory Usage: 7.40GB
dashd Process Memory Usage: 17.21GB - Disk Usage: 12%
Tue 20 Feb 2024 12:49:50 PM WET - CPU Usage: 8.3% - Memory Usage: 7.57GB
dashd Process Memory Usage: 17.40GB - Disk Usage: 12%

Evonode 2 (dashd.pid startdate 21st of January 2024)
RAM : 24GB

Mon 19 Feb 2024 02:33:58 PM WET - CPU Usage: 3% - Memory Usage: 6.78GB
dashd Process Memory Usage: 16.52GB - Disk Usage: 12%
Tue 20 Feb 2024 12:51:08 PM WET - CPU Usage: 3.1% - Memory Usage: 6.91GB
dashd Process Memory Usage: 16.65GB - Disk Usage: 12%

**Comment by qwizzie** [comment]
There is a difference between logging dashd process memory through Ubuntu system, which i have been doing with my shell script containing dashd specific commands (ps -opid,vsz,cmd -C dashd and logging Docker Stats by using a shell script containing Docker-specific commands.

dashd system logging :

![Knipsel0](https://github.com/dashpay/dash/assets/6610543/5f9a33a7-8c1c-499f-b272-8cdd1ec3b510)

Docker Stats logging (with very high CPU usage, so not worth the effort to shell script this through Docker specific commands)  :
  
![Knipsel](https://github.com/dashpay/dash/assets/6610543/0ede0842-e4c6-48f4-ad78-88f7055effac)

I suspect dashd system logging will show a continuous increase towards Docker defined limit of 23.46GB for both Docker containers.
