### ISSUE TITLE
No sigs for 21.1.0??

### ISSUE THREAD

**Issue by nahuhh** [dashpay/dash#6251]
^^

cmon guys.

**Comment by thephez** [comment]
If you're referring to the guix.sigs repo, it looks like the PRs simply haven't been merged in yet (they've been there/approved since the release): https://github.com/dashpay/guix.sigs/pulls?q=is%3Apr+is%3Aopen+21.1.0

@PastaPastaPasta @UdjinM6 can we get those merged?

**Comment by PastaPastaPasta** [comment]
@thephez thanks! merged those. Otherwise, I wrote the following before you responded.

<img width="1455" alt="Screenshot 2024-09-05 at 14 36 24" src="https://github.com/user-attachments/assets/1461dfc7-841a-42ff-9800-01c8d1e1a989">
All these .asc files are the signatures. 

Use on of these guides to verify them
 - [Windows](https://docs.dash.org/en/stable/wallets/dashcore/installation-windows.html?#verifying-dash-core)
 - [MacOS](https://docs.dash.org/en/stable/wallets/dashcore/installation-macos.html?#verifying-dash-core)
 - [Linux](https://docs.dash.org/en/stable/wallets/dashcore/installation-linux.html?#verifying-dash-core)

Additionally, the .exe's and .dmgs are all signed (and notarized if applicable)

see: https://www.virustotal.com/gui/file/8addbaf79f9cfba7b215a0c96f6cbf1013a6da1a9c68fd91cb6e6c707f25cf39 for the exe 
<img width="472" alt="Screenshot 2024-09-05 at 14 38 29" src="https://github.com/user-attachments/assets/dc76e813-ebaa-40b4-b898-93b82205f080">

even the docker images are signed! (although less documented)
`cosign verify --key=dashd.pub dashpay/dashd:21.1.0`(find dashd.pub here https://github.com/dashpay/docker.sigs/blob/master/dashd/dashd.pub)

**Comment by nahuhh** [comment]
Thanks

**Comment by nahuhh** [comment]
Files posted on release page can be modified at will. 

we trust the guix builds and use the committed sigs on that repo to verify binaries

**Comment by PastaPastaPasta** [comment]
Makes sense, yeah, it is best to validate against those signatures, but I guess you're the only person who uses them directly 😂 

Thanks for letting us know
