### ISSUE TITLE
Help Understanding IsBlockPayeeValid

### ISSUE THREAD

**Issue by crowning-** [dashpay/dash#965]
https://github.com/dashpay/dash/blob/master/src/masternode-payments.cpp#L228-234

```
bool IsBlockPayeeValid(const CTransaction& txNew, int nBlockHeight)
{
    if(!masternodeSync.IsSynced()) { //there is no budget data to use to check anything -- find the longest chain
        LogPrint("mnpayments", "Client not synced, skipping block payee checks\n");
        return true;
    }
```

Why does a not fully synced node return the same state as the various successful tests?

**Comment by tgflynn** [comment]
The problem is that you receive blocks and need to validate them before syncing the masternode information.  When the masternode data isn't available you don't have sufficient information to determine if budget payments are valid or not.  So the workaround is to return true here.  It shouldn't be a problem as long as the vast majority of nodes are synced but it's not a perfect solution and I hope we can find something better for 0.12.1.
