### ISSUE TITLE
Masternode crash in CMasternodePayments::CleanPaymentList

### ISSUE THREAD

**Issue by rkorba** [dashpay/dash#977]
My masternode crashes every few weeks with an seg fault. Now i got a core dump. It crashed in masternode-payments.cpp:607
`if(chainActive.Tip()->nHeight` - winner.nBlockHeight > nLimit){
I think it is a race condition because to call chainActive.Tip() there should be cs_main locked, but i am not sure if this is the problem. Btw, I am on the master branch.

**Comment by UdjinM6** [comment]
Thanks for reporting!

Yep, this probably could be it. In 0.12.0.x there are a lot of places where we rely on `chainActive.Tip()` without properly locking it via cs_main because otherwise we ended up in random deadlocks during testing. :/ This `CleanPaymentList` function is a heavy one so locking for entire scope might not be a good idea but we only need height here so limited scope might work well enough. I'll have a look :)

**Comment by UdjinM6** [comment]
Can you help testing #978 pls? Maybe run it for a few days?

**Comment by rkorba** [comment]
Yes, already restarted the masternode. I'll tell you if it crashes again.

**Comment by rkorba** [comment]
No problems with my masternode so far.

**Comment by UdjinM6** [comment]
fixed by #978
